import { Montserrat, Frank_Ruhl_Libre } from 'next/font/google';
import "./globals.css";

export const metadata = {
  title: "Jurri - Lawyer & Consulting Framer Template",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.avif", 
    shortcut: "/favicon.avif",
    apple: "/favicon.avif",
  },
};

const montserrat = Montserrat({
  weight: ['100', '300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
});

const frankRuhlLibre = Frank_Ruhl_Libre({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-frank-ruhl-libre',
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${frankRuhlLibre.variable} antialiased`}>{children}</body>
    </html>
  );
}
